module.exports = {
  "categories": [
    "things a dog would say if they could talk",
    "christmas movies",
    "famous wars",
    "holidays",
    "things you only see at night",
    "things that are too heavy to pickup",
    "famous explorers",
    "things that make you happy",
    "places to sit",
    "olympic sports",
    "things that start with the letter L",
    "things associated with summer",
    "christmas carols",
    "ice hockey teams",
    "pro football teams",
    "found at the grocery store",
    "ways to describe your opponent",
    "famous food brands",
    "ways to get from point a to point b",
    "things with butter inside",
    "musical instrucments",
    "condiments",
    "things that melt in your hand",
    "board games",
    "children toys",
    "words associated with the circus/carnival",
    "types of cheeses",
    "words that begin with a vowel",
    "supervillians",
    "pro baseball teams",
    "words that beginning with the letter y",
    "reasons why cats are better than dogs",
    "junk food",
    "famous athletes",
    "worst jobs",
    "found in a box",
    "smells",
    "apps",
    "modes of transportation",
    "famous actors",
    "description of sounds",
    "types of birds",
    "dog breeds",
    "book titles",
    "places you get lost",
    "fruits",
    "vegetables",
    "types of parties",
    "cartoon characters",
    "things with wings",
    "things made of metal",
    "best tv shows of all time",
    "office or school supplies",
    "candy bars",
    "store names",
    "types of pies",
    "names of relatives",
    "things you cook",
    "cities that have hosted the olympics",
    "1980s bands",
    "types of dinosaurs",
    "things that come in pairs",
    "things associated with travel",
    "broadway musicals",
    "movies from the 1980s",
    "words related to weather",
    "authors",
    "reasons you might be late for something",
    "words related to camping",
    "things you should never do",
    
  ]
}

