module.exports = {
  "categories": [
    "things a dog would say if they could talk",
    "christmas movies",
    "famous wars",
    "holidays",
    "things you only see at night",
    "things that are too heavy to pickup",
    "famous explorers",
    "things that make you happy",
    "places to sit",
    "olympic sports",
    "things that start with the letter L",
    "things associated with summer",
    "christmas carols",
    "ice hockey teams",
    "pro football teams",
    "found at the grocery store",
    "ways to describe your opponent",
    "famous food brands",
    "ways to get from point a to point b",
    "things with buttons",
    "musical instrucments",
    "condiments",
    "things that melt in your hand",
    "things that fit in the palm of your hand",
    "ways to get wet",
    "things that are round",
    "assocated with winter",
    "talk show hosts",
    "children's book title",
    "things that start with the letter s",
    "things assocated with new your city",
    "items found in a pocket",
    "ways to prepare an egg",
    "things that can fly",
    "ice cream flavors",
    "board games",
    "children toys",
    "words associated with the circus/carnival",
    "types of cheeses",
    "words that begin with a vowel",
    "supervillians",
    "pro baseball teams",
    "comedians",
    "best songs from the 1990s",
    "words with more than six letter",
    "things you put on a salad",
    "anmials that eat plants",
    "mythological creatures",
    "things that squish",
    "arnold schwarzenegger movies",
    "songs from the 1970s",
    "songs after the year 2000",
    "words that beginning with the letter y",
    "reasons why cats are better than dogs",
    "junk food",
    "famous athletes",
    "worst jobs",
    "found in a box",
    "smells",
    "apps",
    "modes of transportation",
    "famous actors",
    "description of sounds",
    "types of birds",
    "dog breeds",
    "book titles",
    "places you get lost",
    "fruits",
    "vegetables",
    "types of parties",
    "cartoon characters",
    "things with wings",
    "things made of metal",
    "best tv shows of all time",
    "office or school supplies",
    "candy bars",
    "store names",
    "types of pie",
    "names of relatives",
    "things you cook",
    "hobbies",
    "breakfast cereals",
    "things that scare people",
    "ways to exercise",
    "best musicians of all time",
    "song titles",
    "words you don't like",
    "things you wear on your head",
    "things that are yellow",
    "languages",
    "farm animals",
    "types of wood",
    "things that cut",
    "superheroes",
    "reasons to speed",
    "things that are brown",
    "historical figures",
    "things you turn on & off",
    "animals that would be fun to ride on",
    "found in the bathroom",
    "things associated with cars",
    "cities that have hosted the olympics",
    "1980s bands",
    "types of dinosaurs",
    "things that come in pairs",
    "things associated with travel",
    "broadway musicals",
    "movies from the 1980s",
    "words related to weather",
    "authors",
    "reasons you might be late for something",
    "words related to camping",
    "things you should never do",
    "pizza toppings",
    "car brands",
    "types of flowers",
    "animals smaller than a cat",
    "us cities",
    "clothing brands",
    "things you drink",
    "boy names",
    "girl names",
    "things you can put on",
    "european countries",
    "action movies",
    "types of meat",
    "types of gems",
    "colleges or universities",
    "things you chew on but don't swallow",
    "colors",
    "ways to say 'hello'",
    "us presidents",
    "species of fish",
    "fast food restaurants",
    "found in a kitchen",
    "companies",
    "types of tools",
    "emotions",
    "bad ideas",
    "things on people's heads",
    "bodies of water",
    "things you dig for",
    "things found at the beach",
    "types of pasta",
    "things that start with the letter r",
    "genres of music",
    "found in the garage",
    "things you ride on ",
    "things you see in the sky",
    ""
  ]
}

